-- Update referral settings to use new BSK-based level structure
-- Remove old percentage-based system and implement BSK coin rewards

-- Update existing referral settings to use BSK-based levels
UPDATE referral_settings 
SET levels = '[
  {"level": 1, "bsk_amount": 5.0},
  {"level": 2, "bsk_amount": 0.5},
  {"level": 3, "bsk_amount": 0.5},
  {"level": 4, "bsk_amount": 0.5},
  {"level": 5, "bsk_amount": 0.5},
  {"level": 6, "bsk_amount": 0.5},
  {"level": 7, "bsk_amount": 0.5},
  {"level": 8, "bsk_amount": 0.5},
  {"level": 9, "bsk_amount": 0.5},
  {"level": 10, "bsk_amount": 0.5},
  {"level": 11, "bsk_amount": 0.4},
  {"level": 12, "bsk_amount": 0.4},
  {"level": 13, "bsk_amount": 0.4},
  {"level": 14, "bsk_amount": 0.4},
  {"level": 15, "bsk_amount": 0.4},
  {"level": 16, "bsk_amount": 0.4},
  {"level": 17, "bsk_amount": 0.4},
  {"level": 18, "bsk_amount": 0.4},
  {"level": 19, "bsk_amount": 0.4},
  {"level": 20, "bsk_amount": 0.4},
  {"level": 21, "bsk_amount": 0.3},
  {"level": 22, "bsk_amount": 0.3},
  {"level": 23, "bsk_amount": 0.3},
  {"level": 24, "bsk_amount": 0.3},
  {"level": 25, "bsk_amount": 0.3},
  {"level": 26, "bsk_amount": 0.3},
  {"level": 27, "bsk_amount": 0.3},
  {"level": 28, "bsk_amount": 0.3},
  {"level": 29, "bsk_amount": 0.3},
  {"level": 30, "bsk_amount": 0.3},
  {"level": 31, "bsk_amount": 0.2},
  {"level": 32, "bsk_amount": 0.2},
  {"level": 33, "bsk_amount": 0.2},
  {"level": 34, "bsk_amount": 0.2},
  {"level": 35, "bsk_amount": 0.2},
  {"level": 36, "bsk_amount": 0.2},
  {"level": 37, "bsk_amount": 0.2},
  {"level": 38, "bsk_amount": 0.2},
  {"level": 39, "bsk_amount": 0.2},
  {"level": 40, "bsk_amount": 0.2},
  {"level": 41, "bsk_amount": 0.1},
  {"level": 42, "bsk_amount": 0.1},
  {"level": 43, "bsk_amount": 0.1},
  {"level": 44, "bsk_amount": 0.1},
  {"level": 45, "bsk_amount": 0.1},
  {"level": 46, "bsk_amount": 0.1},
  {"level": 47, "bsk_amount": 0.1},
  {"level": 48, "bsk_amount": 0.1},
  {"level": 49, "bsk_amount": 0.1},
  {"level": 50, "bsk_amount": 0.1}
]'::jsonb,
default_asset_id = (
  SELECT id FROM bonus_assets WHERE symbol = 'BSK' LIMIT 1
)
WHERE id IS NOT NULL;

-- Insert default BSK-based referral settings if none exist
INSERT INTO referral_settings (
  enabled, 
  default_asset_id,
  levels,
  qualifying_actions,
  caps,
  schedule
)
SELECT 
  true,
  (SELECT id FROM bonus_assets WHERE symbol = 'BSK' LIMIT 1),
  '[
    {"level": 1, "bsk_amount": 5.0},
    {"level": 2, "bsk_amount": 0.5},
    {"level": 3, "bsk_amount": 0.5},
    {"level": 4, "bsk_amount": 0.5},
    {"level": 5, "bsk_amount": 0.5},
    {"level": 6, "bsk_amount": 0.5},
    {"level": 7, "bsk_amount": 0.5},
    {"level": 8, "bsk_amount": 0.5},
    {"level": 9, "bsk_amount": 0.5},
    {"level": 10, "bsk_amount": 0.5},
    {"level": 11, "bsk_amount": 0.4},
    {"level": 12, "bsk_amount": 0.4},
    {"level": 13, "bsk_amount": 0.4},
    {"level": 14, "bsk_amount": 0.4},
    {"level": 15, "bsk_amount": 0.4},
    {"level": 16, "bsk_amount": 0.4},
    {"level": 17, "bsk_amount": 0.4},
    {"level": 18, "bsk_amount": 0.4},
    {"level": 19, "bsk_amount": 0.4},
    {"level": 20, "bsk_amount": 0.4},
    {"level": 21, "bsk_amount": 0.3},
    {"level": 22, "bsk_amount": 0.3},
    {"level": 23, "bsk_amount": 0.3},
    {"level": 24, "bsk_amount": 0.3},
    {"level": 25, "bsk_amount": 0.3},
    {"level": 26, "bsk_amount": 0.3},
    {"level": 27, "bsk_amount": 0.3},
    {"level": 28, "bsk_amount": 0.3},
    {"level": 29, "bsk_amount": 0.3},
    {"level": 30, "bsk_amount": 0.3},
    {"level": 31, "bsk_amount": 0.2},
    {"level": 32, "bsk_amount": 0.2},
    {"level": 33, "bsk_amount": 0.2},
    {"level": 34, "bsk_amount": 0.2},
    {"level": 35, "bsk_amount": 0.2},
    {"level": 36, "bsk_amount": 0.2},
    {"level": 37, "bsk_amount": 0.2},
    {"level": 38, "bsk_amount": 0.2},
    {"level": 39, "bsk_amount": 0.2},
    {"level": 40, "bsk_amount": 0.2},
    {"level": 41, "bsk_amount": 0.1},
    {"level": 42, "bsk_amount": 0.1},
    {"level": 43, "bsk_amount": 0.1},
    {"level": 44, "bsk_amount": 0.1},
    {"level": 45, "bsk_amount": 0.1},
    {"level": 46, "bsk_amount": 0.1},
    {"level": 47, "bsk_amount": 0.1},
    {"level": 48, "bsk_amount": 0.1},
    {"level": 49, "bsk_amount": 0.1},
    {"level": 50, "bsk_amount": 0.1}
  ]'::jsonb,
  '["signup", "kyc", "first_trade"]'::jsonb,
  '{"daily_per_user": 100, "global_daily": 10000}'::jsonb,
  'instant'
WHERE NOT EXISTS (SELECT 1 FROM referral_settings);